// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Desc string `json:"desc"`
	User *User  `json:"user"`
}

type NewLink struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Link     []*Link `json:"link"`
}
