// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Userid      string `json:"userid"`
}

type NewLink struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Userid      string `json:"userid"`
}

type UpdateLink struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserLinks struct {
	ID    string  `json:"id"`
	User  *User   `json:"user"`
	Links []*Link `json:"links"`
}
